// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzsxkzgtkjkfkdnjgzdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6c3hremd0a2prZmtkbmpnemRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxNzc4MjMsImV4cCI6MjA1OTc1MzgyM30._yNkjdzlxYPsxr6jD9BPB6usZVnCdk-aLDpqCQPt_vE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);